parameters:
#    tp_assets.example.class: TP\AssetsBundle\Example

services:
#    tp_assets.example:
#        class: %tp_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
