parameters:
#    example.example.class: Essentials\ExampleBundle\Example

services:
#    example.example:
#        class: %example.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
